name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    name: Python ${{ matrix.python-version }} Tests

    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      # https://github.com/marketplace/actions/setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install pytest
        sudo apt install -y protobuf-compiler
        pip install .
        mkdir resources
        wget -nc -q "https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.ftz" -O "resources/lid.176.ftz"

    - name: Lint with flake8
      run: |
        flake8 --ignore=E501,W503

    - name: Unit Test with pytest
      run: |
        pytest
